import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
const inter = Inter({ subsets: ["latin"] });
import SearchAppBar from '@/components/Navbar';
import LabelBottomNavigation from '@/components/BottomNavigation';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider
          options={{ key: 'css' }}
        >
          <ThemeProvider theme={theme}>
            <SearchAppBar />
              {children}
            <LabelBottomNavigation />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
